"""add_address_column_in_orders

Revision ID: 6130ab72cc7b
Revises: fe6c58c25011
Create Date: 2025-09-11 10:30:47.999444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6130ab72cc7b'
down_revision: Union[str, None] = 'fe6c58c25011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carts_ibfk_1', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'])
    op.add_column('orders', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('postal_code', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('phone', sa.String(length=20), nullable=False))
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', mysql.TEXT(), nullable=False))
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'postal_code')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_ibfk_1', 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
